[env:generic-ln882h]
platform = libretiny
board = generic-ln882h
framework = arduino

custom_board = custom_board.json
monitor_speed = 115200

extra_scripts = pre:scripts/buildtime.py

lib_ldf_mode = deep+

build_unflags =
    -std=gnu++11

build_flags =
    -DCONFIG_LT_AUTO_OTA=1
    -DLFS_START_ADDR=0x188000
    -DLFS_SIZE=0x78000
    -DLFS_BLOCK_SIZE=4096
    -DLFS_NAME_MAX=48
    -DLFS_THREADSAFE=1
    -DLFS_BLOCK_CYCLES=512
    -DLT_UART_DEFAULT_PORT=0
    -DICACHE_RAM_ATTR=
    -std=gnu++14

    -DLT_LOGLEVEL=1
    -DLT_LOGGER_CALLER=1
    -DLT_LOGGER_TIMESTAMP=0

    -DLT_DEBUG_SYS=1
    -DLT_DEBUG_CFG=1
    -DLT_DEBUG_CMD=1
    -DLT_DEBUG_WS=1
    -DLT_DEBUG_PUMP=1
    -DLT_DEBUG_NET=1
    -DLT_DEBUG_BTN=1
    -DLT_DEBUG_LITTLEFS=1

    -DMBEDTLS_SSL_IN_CONTENT_LEN=8*1024

    -DWEBSOCKETS_SERVER_CLIENT_MAX=2

    -Wl,--wrap=putchar_p

